### ISSUE TITLE
<h1>429 Too Many Requests</h1>

### ISSUE THREAD

**Issue by foggy54** [falconshark/boosty-crawler#1]
Hello, when I'm trying to DL images, I'm getting error <h1>429 Too Many Requests</h1>, is it possible to do something about that? 
And second Q  - do I need to set auth cookie in the config.json, or something other?

**Comment by falconshark** [comment]
Hello, sorry for late reply.
I am not sure why there will be too many requests, could you provide your image URL for me for checking it?
And then, yes, you should setup the auth cookie in config.json, otherwise you will not able to download the image.
